import{
	argbFromHex,
	hexFromArgb,
	Hct
}from"https://esm.sh/@material/material-color-utilities"
import{
	q
}from"./util.js"
document.getElementById("3").addEventListener("keydown",(w)=>{
	if(w.key==="Enter"){
		document.getElementById("5").innerHTML=q(Hct.from(+document.getElementById("1").value,+document.getElementById("2").value,+document.getElementById("3").value),hexFromArgb)
	}
})
document.getElementById("4").addEventListener("keydown",(e)=>{
	if(e.key==="Enter"){
		document.getElementById("5").innerHTML=q(Hct.fromInt(argbFromHex(document.getElementById("4").value)),hexFromArgb)
	}
})